"""Generate agents.json — a curated catalogue of 400+ specialised agents.

Each agent is a data record, not a service. The runtime loads this file and
drives every entry through the same GenericAgent class.

Run:  python gen_agents.py   ->  writes agents.json
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# domain -> (capabilities, tools, cost, risk, permissions, verification)
DOMAINS: dict[str, dict] = {
    "software_architecture": dict(caps=["architecture", "design", "planning"], tools=["filesystem"],
                                  cost="medium", risk="low", perms=["fs:read", "delegate"], verify="quality"),
    "backend_engineering": dict(caps=["backend", "code", "api"], tools=["filesystem", "sqlite"],
                                cost="medium", risk="medium", perms=["fs:read", "fs:write", "db:query"], verify="code"),
    "frontend_engineering": dict(caps=["frontend", "code", "ui"], tools=["filesystem"],
                                 cost="medium", risk="medium", perms=["fs:read", "fs:write"], verify="code"),
    "mobile_engineering": dict(caps=["mobile", "code", "ui"], tools=["filesystem"],
                               cost="medium", risk="medium", perms=["fs:read", "fs:write"], verify="code"),
    "game_development": dict(caps=["game", "code", "graphics"], tools=["filesystem"],
                             cost="medium", risk="medium", perms=["fs:read", "fs:write"], verify="code"),
    "embedded_systems": dict(caps=["embedded", "code", "hardware"], tools=["filesystem"],
                             cost="medium", risk="high", perms=["fs:read", "fs:write"], verify="code"),
    "data_engineering": dict(caps=["data", "pipeline", "code"], tools=["filesystem", "sqlite"],
                             cost="medium", risk="medium", perms=["fs:read", "fs:write", "db:query"], verify="code"),
    "data_science": dict(caps=["analysis", "statistics", "data"], tools=["filesystem", "sqlite"],
                         cost="medium", risk="low", perms=["fs:read", "db:query"], verify="factual"),
    "machine_learning": dict(caps=["ml", "modeling", "code"], tools=["filesystem"],
                             cost="high", risk="medium", perms=["fs:read", "fs:write"], verify="code"),
    "mlops": dict(caps=["mlops", "deploy", "monitoring"], tools=["filesystem"],
                  cost="medium", risk="high", perms=["fs:read", "fs:write"], verify="completion"),
    "devops": dict(caps=["devops", "ci", "automation"], tools=["filesystem"],
                   cost="medium", risk="high", perms=["fs:read", "fs:write"], verify="completion"),
    "cloud_infrastructure": dict(caps=["cloud", "infrastructure", "networking"], tools=["filesystem"],
                                 cost="medium", risk="high", perms=["fs:read", "fs:write"], verify="security"),
    "site_reliability": dict(caps=["reliability", "monitoring", "operations"], tools=["filesystem"],
                             cost="medium", risk="high", perms=["fs:read"], verify="completion"),
    "security": dict(caps=["security", "review", "threat"], tools=["filesystem"],
                     cost="high", risk="low", perms=["fs:read"], verify="security"),
    "privacy_compliance": dict(caps=["privacy", "compliance", "governance"], tools=["filesystem"],
                               cost="medium", risk="low", perms=["fs:read"], verify="security"),
    "quality_assurance": dict(caps=["testing", "qa", "code"], tools=["filesystem"],
                              cost="low", risk="low", perms=["fs:read", "fs:write"], verify="tests"),
    "database": dict(caps=["database", "schema", "sql"], tools=["sqlite", "filesystem"],
                     cost="medium", risk="medium", perms=["db:query", "fs:read"], verify="code"),
    "api_design": dict(caps=["api", "contract", "integration"], tools=["filesystem"],
                       cost="low", risk="low", perms=["fs:read", "fs:write"], verify="quality"),
    "product_management": dict(caps=["product", "requirements", "planning"], tools=["filesystem"],
                               cost="low", risk="low", perms=["fs:read", "delegate"], verify="quality"),
    "ux_design": dict(caps=["ux", "design", "research"], tools=["filesystem"],
                      cost="low", risk="low", perms=["fs:read"], verify="quality"),
    "technical_writing": dict(caps=["documentation", "writing", "communication"], tools=["filesystem"],
                              cost="low", risk="low", perms=["fs:read", "fs:write"], verify="quality"),
    "research": dict(caps=["research", "synthesis", "evidence"], tools=["fetch"],
                     cost="medium", risk="low", perms=["net:fetch"], verify="factual"),
    "scientific_computing": dict(caps=["science", "simulation", "numerical"], tools=["filesystem"],
                                 cost="high", risk="low", perms=["fs:read", "fs:write"], verify="factual"),
    "bioinformatics": dict(caps=["biology", "genomics", "data"], tools=["filesystem"],
                           cost="high", risk="low", perms=["fs:read"], verify="factual"),
    "healthcare": dict(caps=["health", "clinical", "documentation"], tools=["fetch"],
                       cost="medium", risk="high", perms=["net:fetch"], verify="factual"),
    "legal": dict(caps=["legal", "contracts", "policy"], tools=["filesystem", "fetch"],
                  cost="medium", risk="high", perms=["fs:read", "net:fetch"], verify="factual"),
    "finance": dict(caps=["finance", "modeling", "analysis"], tools=["filesystem", "sqlite"],
                    cost="medium", risk="high", perms=["fs:read", "db:query"], verify="factual"),
    "accounting": dict(caps=["accounting", "reporting", "controls"], tools=["filesystem", "sqlite"],
                       cost="low", risk="high", perms=["fs:read", "db:query"], verify="factual"),
    "marketing": dict(caps=["marketing", "content", "growth"], tools=["fetch", "filesystem"],
                      cost="low", risk="low", perms=["net:fetch", "fs:write"], verify="quality"),
    "sales": dict(caps=["sales", "outreach", "crm"], tools=["filesystem"],
                  cost="low", risk="low", perms=["fs:read", "fs:write"], verify="quality"),
    "customer_support": dict(caps=["support", "communication", "triage"], tools=["filesystem"],
                             cost="low", risk="low", perms=["fs:read"], verify="quality"),
    "human_resources": dict(caps=["hr", "people", "policy"], tools=["filesystem"],
                            cost="low", risk="medium", perms=["fs:read"], verify="quality"),
    "operations": dict(caps=["operations", "process", "logistics"], tools=["filesystem", "sqlite"],
                       cost="low", risk="low", perms=["fs:read", "db:query"], verify="completion"),
    "analytics": dict(caps=["analytics", "metrics", "reporting"], tools=["sqlite", "filesystem"],
                      cost="low", risk="low", perms=["db:query", "fs:read"], verify="factual"),
    "creative_writing": dict(caps=["writing", "narrative", "creative"], tools=["filesystem"],
                             cost="low", risk="low", perms=["fs:write"], verify="quality"),
    "media_production": dict(caps=["media", "audio", "video"], tools=["filesystem"],
                             cost="medium", risk="low", perms=["fs:read", "fs:write"], verify="quality"),
    "education": dict(caps=["education", "curriculum", "explanation"], tools=["filesystem", "fetch"],
                      cost="low", risk="low", perms=["fs:read", "net:fetch"], verify="quality"),
    "blockchain": dict(caps=["blockchain", "smart_contracts", "code"], tools=["filesystem"],
                       cost="high", risk="high", perms=["fs:read", "fs:write"], verify="security"),
    "localization": dict(caps=["localization", "translation", "content"], tools=["filesystem"],
                         cost="low", risk="low", perms=["fs:read", "fs:write"], verify="quality"),
    "orchestration": dict(caps=["planning", "coordination", "reasoning"], tools=[],
                          cost="medium", risk="low", perms=["delegate"], verify="quality"),
}

# domain -> list of (role_slug, Display Name, what it does)
ROLES: dict[str, list[tuple[str, str, str]]] = {
    "software_architecture": [
        ("system_designer", "System Designer", "designs end-to-end system topology and service boundaries"),
        ("domain_modeler", "Domain Modeler", "builds domain models, bounded contexts and ubiquitous language"),
        ("integration_architect", "Integration Architect", "designs integration patterns between internal and third-party systems"),
        ("event_architect", "Event Architect", "designs event-driven flows, topics, ordering and delivery guarantees"),
        ("migration_planner", "Migration Planner", "plans incremental migrations with rollback and dual-write strategies"),
        ("scalability_architect", "Scalability Architect", "designs for horizontal scale, sharding and load distribution"),
        ("resilience_architect", "Resilience Architect", "designs failure domains, bulkheads, retries and circuit breakers"),
        ("tech_selector", "Technology Selector", "evaluates and selects frameworks, datastores and runtimes with tradeoffs"),
        ("adr_author", "ADR Author", "records architecture decisions with context, options and consequences"),
        ("legacy_analyst", "Legacy Analyst", "reverse-engineers legacy systems and maps modernisation paths"),
        ("cost_architect", "Cost Architect", "designs architectures against an explicit cost envelope"),
        ("multitenancy_architect", "Multi-Tenancy Architect", "designs tenant isolation, routing and noisy-neighbour controls"),
    ],
    "backend_engineering": [
        ("api_implementer", "API Implementer", "implements HTTP/gRPC endpoints with validation and error handling"),
        ("service_builder", "Service Builder", "builds standalone services with config, logging and health checks"),
        ("worker_engineer", "Worker Engineer", "implements background workers, queues and scheduled jobs"),
        ("auth_engineer", "Auth Engineer", "implements authentication, sessions, tokens and password flows"),
        ("authz_engineer", "Authorization Engineer", "implements RBAC/ABAC policies and permission checks"),
        ("caching_engineer", "Caching Engineer", "designs and implements cache layers, keys and invalidation"),
        ("payments_engineer", "Payments Engineer", "implements billing, subscriptions, webhooks and idempotency"),
        ("search_engineer", "Search Engineer", "implements indexing, query parsing and ranking"),
        ("notification_engineer", "Notification Engineer", "implements email, push and in-app notification delivery"),
        ("file_storage_engineer", "File Storage Engineer", "implements uploads, object storage and signed URLs"),
        ("realtime_engineer", "Realtime Engineer", "implements WebSockets, SSE and presence"),
        ("refactoring_engineer", "Refactoring Engineer", "restructures code for clarity without changing behaviour"),
    ],
    "frontend_engineering": [
        ("component_builder", "Component Builder", "builds reusable typed UI components"),
        ("state_engineer", "State Engineer", "designs client state, caching and data fetching"),
        ("form_engineer", "Form Engineer", "builds validated, accessible forms with good error states"),
        ("routing_engineer", "Routing Engineer", "designs route structure, guards and code splitting"),
        ("styling_engineer", "Styling Engineer", "implements design tokens, themes and responsive layout"),
        ("accessibility_engineer", "Accessibility Engineer", "audits and fixes WCAG issues, keyboard and screen-reader support"),
        ("perf_engineer", "Frontend Performance Engineer", "reduces bundle size, render cost and Core Web Vitals"),
        ("dataviz_engineer", "Data Visualisation Engineer", "builds charts and interactive visualisations"),
        ("i18n_engineer", "Internationalisation Engineer", "wires locale, formatting and RTL support"),
        ("animation_engineer", "Animation Engineer", "implements motion with reduced-motion fallbacks"),
        ("ssr_engineer", "SSR Engineer", "implements server rendering, hydration and streaming"),
        ("offline_engineer", "Offline Engineer", "implements service workers, caching and sync"),
    ],
    "mobile_engineering": [
        ("ios_engineer", "iOS Engineer", "builds native iOS features and views"),
        ("android_engineer", "Android Engineer", "builds native Android features and views"),
        ("cross_platform_engineer", "Cross-Platform Engineer", "builds shared React Native / Flutter features"),
        ("mobile_state_engineer", "Mobile State Engineer", "designs local persistence and offline-first state"),
        ("mobile_perf_engineer", "Mobile Performance Engineer", "reduces startup time, jank and battery drain"),
        ("push_engineer", "Push Notification Engineer", "implements push registration, delivery and deep links"),
        ("mobile_release_engineer", "Mobile Release Engineer", "prepares store builds, signing and staged rollout"),
        ("mobile_ux_engineer", "Mobile UX Engineer", "adapts flows to touch, gestures and small screens"),
        ("mobile_security_engineer", "Mobile Security Engineer", "secures local storage, certs and jailbreak handling"),
        ("mobile_test_engineer", "Mobile Test Engineer", "writes device and simulator test suites"),
        ("wearables_engineer", "Wearables Engineer", "builds companion watch and wearable experiences"),
        ("mobile_analytics_engineer", "Mobile Analytics Engineer", "instruments funnels and retention events"),
    ],
    "game_development": [
        ("gameplay_engineer", "Gameplay Engineer", "implements core mechanics and player controls"),
        ("game_designer", "Game Designer", "designs loops, progression and difficulty curves"),
        ("level_designer", "Level Designer", "designs levels, pacing and encounter layout"),
        ("physics_engineer", "Physics Engineer", "implements collision, movement and simulation"),
        ("graphics_engineer", "Graphics Engineer", "implements shaders, lighting and rendering pipelines"),
        ("game_ai_engineer", "Game AI Engineer", "implements NPC behaviour, pathfinding and state machines"),
        ("netcode_engineer", "Netcode Engineer", "implements multiplayer sync, prediction and rollback"),
        ("game_audio_engineer", "Game Audio Engineer", "implements adaptive audio and mixing"),
        ("game_ui_engineer", "Game UI Engineer", "implements HUD, menus and input remapping"),
        ("game_perf_engineer", "Game Performance Engineer", "profiles and optimises frame time and memory"),
        ("game_economy_designer", "Game Economy Designer", "designs currencies, sinks and balance"),
        ("game_tools_engineer", "Game Tools Engineer", "builds editor tooling and content pipelines"),
    ],
    "embedded_systems": [
        ("firmware_engineer", "Firmware Engineer", "writes firmware for microcontrollers and peripherals"),
        ("rtos_engineer", "RTOS Engineer", "designs task scheduling, priorities and timing"),
        ("driver_engineer", "Driver Engineer", "implements device drivers and bus protocols"),
        ("power_engineer", "Power Engineer", "optimises sleep states and energy budgets"),
        ("signal_engineer", "Signal Processing Engineer", "implements filtering and sensor fusion"),
        ("bootloader_engineer", "Bootloader Engineer", "implements secure boot and OTA update flows"),
        ("hardware_test_engineer", "Hardware Test Engineer", "designs bring-up and hardware-in-loop tests"),
        ("protocol_engineer", "Protocol Engineer", "implements CAN, Modbus, BLE and serial protocols"),
        ("memory_engineer", "Memory Engineer", "optimises RAM/flash layout and avoids fragmentation"),
        ("safety_engineer", "Functional Safety Engineer", "applies safety standards and failure analysis"),
        ("edge_ml_engineer", "Edge ML Engineer", "quantises and deploys models to constrained devices"),
        ("embedded_security_engineer", "Embedded Security Engineer", "secures keys, debug ports and update chains"),
    ],
    "data_engineering": [
        ("pipeline_builder", "Pipeline Builder", "builds batch and streaming ingestion pipelines"),
        ("etl_engineer", "ETL Engineer", "implements extract, transform and load steps"),
        ("warehouse_modeler", "Warehouse Modeler", "designs star/snowflake models and marts"),
        ("cdc_engineer", "CDC Engineer", "implements change data capture and replication"),
        ("data_quality_engineer", "Data Quality Engineer", "implements expectations, nulls and drift checks"),
        ("orchestration_engineer", "Orchestration Engineer", "implements DAG scheduling and backfills"),
        ("streaming_engineer", "Streaming Engineer", "implements windowing, watermarks and exactly-once"),
        ("lakehouse_engineer", "Lakehouse Engineer", "designs partitioning, compaction and table formats"),
        ("data_contract_engineer", "Data Contract Engineer", "defines and enforces producer/consumer schemas"),
        ("ingestion_connector_engineer", "Connector Engineer", "builds source connectors with incremental sync"),
        ("data_catalog_engineer", "Data Catalog Engineer", "documents lineage, ownership and definitions"),
        ("data_cost_engineer", "Data Cost Engineer", "reduces storage and compute spend in pipelines"),
    ],
    "data_science": [
        ("eda_analyst", "EDA Analyst", "profiles datasets and surfaces distributions and anomalies"),
        ("feature_engineer", "Feature Engineer", "designs and validates predictive features"),
        ("experiment_designer", "Experiment Designer", "designs A/B tests with power analysis"),
        ("causal_analyst", "Causal Analyst", "estimates causal effects and controls for confounders"),
        ("forecasting_analyst", "Forecasting Analyst", "builds time-series forecasts with uncertainty bands"),
        ("segmentation_analyst", "Segmentation Analyst", "clusters populations into actionable segments"),
        ("survey_analyst", "Survey Analyst", "designs instruments and analyses response data"),
        ("statistical_reviewer", "Statistical Reviewer", "audits methods for bias, leakage and misuse"),
        ("data_storyteller", "Data Storyteller", "turns analysis into a decision narrative"),
        ("anomaly_analyst", "Anomaly Analyst", "detects and explains outliers in data"),
        ("cohort_analyst", "Cohort Analyst", "builds retention and cohort analyses"),
        ("sampling_analyst", "Sampling Analyst", "designs sampling strategies and weighting"),
    ],
    "machine_learning": [
        ("model_trainer", "Model Trainer", "sets up training loops, schedules and checkpoints"),
        ("model_evaluator", "Model Evaluator", "designs metrics, splits and error analysis"),
        ("nlp_engineer", "NLP Engineer", "builds text classification, extraction and generation"),
        ("vision_engineer", "Vision Engineer", "builds image and video models"),
        ("recsys_engineer", "RecSys Engineer", "builds ranking and recommendation systems"),
        ("finetuning_engineer", "Fine-Tuning Engineer", "prepares datasets and runs supervised fine-tunes"),
        ("rag_engineer", "RAG Engineer", "builds retrieval-augmented pipelines and chunking"),
        ("embedding_engineer", "Embedding Engineer", "selects and evaluates embedding models and indexes"),
        ("prompt_engineer", "Prompt Engineer", "designs, tests and versions prompts against evals"),
        ("eval_engineer", "Eval Engineer", "builds automated evaluation suites and graders"),
        ("interpretability_analyst", "Interpretability Analyst", "explains model behaviour and failure modes"),
        ("optimisation_engineer", "Optimisation Engineer", "tunes hyperparameters and inference cost"),
    ],
    "mlops": [
        ("model_deployer", "Model Deployer", "packages and serves models behind stable interfaces"),
        ("model_monitor", "Model Monitor", "tracks drift, latency and quality in production"),
        ("feature_store_engineer", "Feature Store Engineer", "manages offline/online feature parity"),
        ("model_registry_engineer", "Model Registry Engineer", "versions models, lineage and approvals"),
        ("inference_optimiser", "Inference Optimiser", "batches, quantises and caches inference"),
        ("training_infra_engineer", "Training Infra Engineer", "manages GPU scheduling and distributed training"),
        ("data_versioning_engineer", "Data Versioning Engineer", "snapshots and versions training data"),
        ("shadow_deploy_engineer", "Shadow Deploy Engineer", "runs shadow and canary model rollouts"),
        ("rollback_engineer", "Model Rollback Engineer", "defines rollback triggers and safe defaults"),
        ("ml_cost_engineer", "ML Cost Engineer", "reduces training and serving spend"),
        ("reproducibility_engineer", "Reproducibility Engineer", "pins seeds, environments and artefacts"),
        ("ml_pipeline_engineer", "ML Pipeline Engineer", "automates retraining and promotion pipelines"),
    ],
    "devops": [
        ("ci_engineer", "CI Engineer", "builds fast, cacheable CI pipelines"),
        ("cd_engineer", "CD Engineer", "builds progressive delivery and rollback pipelines"),
        ("container_engineer", "Container Engineer", "writes minimal, reproducible container images"),
        ("iac_engineer", "IaC Engineer", "writes declarative infrastructure with state management"),
        ("secrets_engineer", "Secrets Engineer", "manages secret storage, rotation and injection"),
        ("build_engineer", "Build Engineer", "optimises build graphs and artefact caching"),
        ("release_manager", "Release Manager", "coordinates versioning, changelogs and release gates"),
        ("environment_engineer", "Environment Engineer", "manages dev/stage/prod parity and seeding"),
        ("dependency_engineer", "Dependency Engineer", "manages upgrades, pinning and vulnerability patching"),
        ("artifact_engineer", "Artifact Engineer", "manages registries, retention and provenance"),
        ("runbook_author", "Runbook Author", "writes actionable operational runbooks"),
        ("chaos_engineer", "Chaos Engineer", "designs controlled failure experiments"),
    ],
    "cloud_infrastructure": [
        ("network_engineer", "Network Engineer", "designs VPCs, subnets, routing and egress control"),
        ("compute_engineer", "Compute Engineer", "sizes and configures compute and autoscaling"),
        ("storage_engineer", "Storage Engineer", "designs durable storage, tiering and lifecycle"),
        ("kubernetes_engineer", "Kubernetes Engineer", "writes manifests, operators and resource policy"),
        ("service_mesh_engineer", "Service Mesh Engineer", "configures mTLS, routing and traffic policy"),
        ("dns_engineer", "DNS Engineer", "manages zones, records and failover routing"),
        ("cdn_engineer", "CDN Engineer", "configures edge caching, invalidation and headers"),
        ("load_balancer_engineer", "Load Balancer Engineer", "configures health checks and traffic distribution"),
        ("backup_engineer", "Backup Engineer", "designs backup, restore and retention policy"),
        ("dr_engineer", "Disaster Recovery Engineer", "designs RPO/RTO and failover drills"),
        ("cloud_cost_engineer", "Cloud Cost Engineer", "rightsizes resources and reduces spend"),
        ("edge_engineer", "Edge Engineer", "designs edge compute placement and routing"),
    ],
    "site_reliability": [
        ("slo_engineer", "SLO Engineer", "defines SLIs, SLOs and error budgets"),
        ("alerting_engineer", "Alerting Engineer", "designs actionable alerts and reduces noise"),
        ("incident_commander", "Incident Commander", "coordinates incident response and communication"),
        ("postmortem_author", "Postmortem Author", "writes blameless postmortems with actions"),
        ("capacity_planner", "Capacity Planner", "forecasts load and plans headroom"),
        ("latency_analyst", "Latency Analyst", "traces and reduces tail latency"),
        ("tracing_engineer", "Tracing Engineer", "instruments distributed traces and spans"),
        ("logging_engineer", "Logging Engineer", "designs structured logging and retention"),
        ("metrics_engineer", "Metrics Engineer", "designs cardinality-safe metrics"),
        ("oncall_designer", "On-Call Designer", "designs rotations, escalation and handoffs"),
        ("toil_reducer", "Toil Reducer", "automates repetitive operational work"),
        ("dependency_risk_analyst", "Dependency Risk Analyst", "maps critical dependencies and failure blast radius"),
    ],
    "security": [
        ("threat_modeler", "Threat Modeler", "builds threat models and abuse cases"),
        ("appsec_reviewer", "AppSec Reviewer", "reviews code for injection, authz and crypto flaws"),
        ("secrets_auditor", "Secrets Auditor", "detects leaked credentials and weak storage"),
        ("dependency_auditor", "Dependency Auditor", "identifies vulnerable and abandoned dependencies"),
        ("crypto_reviewer", "Cryptography Reviewer", "reviews key management and algorithm choices"),
        ("iam_reviewer", "IAM Reviewer", "reviews roles, scopes and least privilege"),
        ("network_security_reviewer", "Network Security Reviewer", "reviews exposure, egress and segmentation"),
        ("ssrf_reviewer", "SSRF Reviewer", "reviews outbound request handling and allowlists"),
        ("supply_chain_auditor", "Supply Chain Auditor", "reviews build provenance and signing"),
        ("prompt_injection_reviewer", "Prompt Injection Reviewer", "reviews LLM input handling and tool exposure"),
        ("hardening_engineer", "Hardening Engineer", "applies platform and container hardening baselines"),
        ("security_test_designer", "Security Test Designer", "designs abuse-case and fuzz test suites"),
    ],
    "privacy_compliance": [
        ("dpia_author", "DPIA Author", "runs data protection impact assessments"),
        ("data_mapper", "Data Mapper", "maps personal data flows and retention"),
        ("consent_designer", "Consent Designer", "designs consent capture and withdrawal flows"),
        ("retention_designer", "Retention Designer", "designs deletion and minimisation policy"),
        ("gdpr_reviewer", "GDPR Reviewer", "reviews lawful basis, rights and transfers"),
        ("hipaa_reviewer", "HIPAA Reviewer", "reviews PHI handling and safeguards"),
        ("soc2_reviewer", "SOC 2 Reviewer", "maps controls to trust services criteria"),
        ("pci_reviewer", "PCI Reviewer", "reviews cardholder data scope and controls"),
        ("audit_evidence_collector", "Audit Evidence Collector", "assembles control evidence packages"),
        ("policy_author", "Policy Author", "drafts internal security and privacy policy"),
        ("vendor_risk_reviewer", "Vendor Risk Reviewer", "assesses third-party processor risk"),
        ("ai_governance_reviewer", "AI Governance Reviewer", "reviews model use against internal AI policy"),
    ],
    "quality_assurance": [
        ("unit_test_writer", "Unit Test Writer", "writes focused unit tests with clear assertions"),
        ("integration_test_writer", "Integration Test Writer", "writes tests across service boundaries"),
        ("e2e_test_writer", "E2E Test Writer", "writes user-journey tests"),
        ("property_test_writer", "Property Test Writer", "writes property-based and fuzz tests"),
        ("regression_analyst", "Regression Analyst", "bisects and characterises regressions"),
        ("test_data_designer", "Test Data Designer", "builds realistic fixtures and factories"),
        ("coverage_analyst", "Coverage Analyst", "finds untested branches that matter"),
        ("flaky_test_fixer", "Flaky Test Fixer", "diagnoses and stabilises non-deterministic tests"),
        ("load_test_engineer", "Load Test Engineer", "designs load profiles and measures saturation"),
        ("contract_test_engineer", "Contract Test Engineer", "writes consumer-driven contract tests"),
        ("accessibility_tester", "Accessibility Tester", "tests keyboard, contrast and semantics"),
        ("exploratory_tester", "Exploratory Tester", "probes for unexpected behaviour and edge cases"),
    ],
    "database": [
        ("schema_designer", "Schema Designer", "designs normalised schemas and constraints"),
        ("index_optimiser", "Index Optimiser", "designs indexes from query patterns"),
        ("query_optimiser", "Query Optimiser", "rewrites slow queries and reads plans"),
        ("migration_writer", "Migration Writer", "writes safe, reversible migrations"),
        ("partitioning_engineer", "Partitioning Engineer", "designs partitions and archival strategy"),
        ("replication_engineer", "Replication Engineer", "configures replicas, lag and failover"),
        ("db_backup_engineer", "DB Backup Engineer", "designs PITR and restore verification"),
        ("transaction_analyst", "Transaction Analyst", "reviews isolation levels and deadlocks"),
        ("nosql_modeler", "NoSQL Modeler", "designs access-pattern-first document/key models"),
        ("vector_db_engineer", "Vector DB Engineer", "designs vector indexes and hybrid search"),
        ("db_security_reviewer", "DB Security Reviewer", "reviews grants, row-level security and encryption"),
        ("db_capacity_planner", "DB Capacity Planner", "forecasts growth and connection limits"),
    ],
    "api_design": [
        ("rest_designer", "REST Designer", "designs resources, verbs and status semantics"),
        ("graphql_designer", "GraphQL Designer", "designs schemas, resolvers and depth limits"),
        ("grpc_designer", "gRPC Designer", "designs protobuf contracts and streaming"),
        ("webhook_designer", "Webhook Designer", "designs delivery, retries and signature verification"),
        ("versioning_designer", "API Versioning Designer", "designs deprecation and compatibility policy"),
        ("pagination_designer", "Pagination Designer", "designs cursor and offset pagination"),
        ("error_model_designer", "Error Model Designer", "designs consistent machine-readable errors"),
        ("sdk_designer", "SDK Designer", "designs ergonomic client libraries"),
        ("openapi_author", "OpenAPI Author", "writes accurate specs and examples"),
        ("rate_limit_designer", "Rate Limit Designer", "designs quotas, headers and backoff guidance"),
        ("idempotency_designer", "Idempotency Designer", "designs safe retries and idempotency keys"),
        ("api_docs_author", "API Docs Author", "writes task-oriented API documentation"),
    ],
    "product_management": [
        ("goal_analyzer", "Goal Analyzer", "turns vague goals into scope, constraints and acceptance criteria"),
        ("requirements_writer", "Requirements Writer", "writes functional and non-functional requirements"),
        ("user_story_writer", "User Story Writer", "writes stories with acceptance criteria"),
        ("prioritiser", "Prioritiser", "ranks work by impact, effort and risk"),
        ("roadmap_planner", "Roadmap Planner", "sequences work into themed releases"),
        ("competitive_analyst", "Competitive Analyst", "compares alternatives and positioning"),
        ("pricing_analyst", "Pricing Analyst", "models packaging and price sensitivity"),
        ("metrics_definer", "Metrics Definer", "defines north-star and guardrail metrics"),
        ("discovery_interviewer", "Discovery Interviewer", "designs interview guides and synthesises findings"),
        ("scope_cutter", "Scope Cutter", "finds the smallest valuable slice"),
        ("launch_planner", "Launch Planner", "plans launch checklists and comms"),
        ("feedback_synthesiser", "Feedback Synthesiser", "clusters user feedback into themes"),
    ],
    "ux_design": [
        ("flow_designer", "Flow Designer", "maps task flows and decision points"),
        ("wireframer", "Wireframer", "describes low-fidelity layouts and hierarchy"),
        ("interaction_designer", "Interaction Designer", "specifies states, transitions and feedback"),
        ("information_architect", "Information Architect", "structures navigation and labelling"),
        ("content_designer", "Content Designer", "writes interface copy and empty states"),
        ("design_system_author", "Design System Author", "defines tokens, components and usage rules"),
        ("usability_reviewer", "Usability Reviewer", "runs heuristic evaluation and finds friction"),
        ("onboarding_designer", "Onboarding Designer", "designs activation and first-run experience"),
        ("error_experience_designer", "Error Experience Designer", "designs recovery-oriented error states"),
        ("form_ux_designer", "Form UX Designer", "reduces form friction and validation pain"),
        ("mobile_ux_designer", "Mobile UX Designer", "adapts patterns to touch and small screens"),
        ("research_synthesiser", "UX Research Synthesiser", "turns research into design implications"),
    ],
    "technical_writing": [
        ("readme_author", "README Author", "writes clear project READMEs"),
        ("tutorial_author", "Tutorial Author", "writes step-by-step learning paths"),
        ("reference_author", "Reference Author", "writes precise reference documentation"),
        ("changelog_author", "Changelog Author", "writes user-facing change summaries"),
        ("architecture_doc_author", "Architecture Doc Author", "documents systems for new engineers"),
        ("migration_guide_author", "Migration Guide Author", "writes upgrade and breaking-change guides"),
        ("troubleshooting_author", "Troubleshooting Author", "writes symptom-first diagnostic guides"),
        ("glossary_author", "Glossary Author", "defines consistent domain terminology"),
        ("style_guide_author", "Style Guide Author", "defines documentation voice and conventions"),
        ("doc_reviewer", "Doc Reviewer", "edits for accuracy, clarity and structure"),
        ("comment_writer", "Code Comment Writer", "writes comments that explain intent, not syntax"),
        ("diagram_describer", "Diagram Describer", "specifies diagrams in text form for rendering"),
    ],
    "research": [
        ("literature_reviewer", "Literature Reviewer", "surveys prior work and summarises consensus"),
        ("source_verifier", "Source Verifier", "checks claims against primary sources"),
        ("market_researcher", "Market Researcher", "researches market size, players and trends"),
        ("technical_researcher", "Technical Researcher", "researches implementation approaches and tradeoffs"),
        ("patent_researcher", "Patent Researcher", "surveys patent landscape and prior art"),
        ("standards_researcher", "Standards Researcher", "locates and interprets relevant standards"),
        ("benchmark_researcher", "Benchmark Researcher", "finds and compares published benchmarks"),
        ("citation_manager", "Citation Manager", "tracks and formats references"),
        ("contradiction_finder", "Contradiction Finder", "surfaces disagreement between sources"),
        ("gap_analyst", "Gap Analyst", "identifies what is not yet known"),
        ("methodology_reviewer", "Methodology Reviewer", "critiques study design and validity"),
        ("evidence_grader", "Evidence Grader", "rates strength and applicability of evidence"),
    ],
    "scientific_computing": [
        ("numerical_modeler", "Numerical Modeler", "formulates and discretises numerical models"),
        ("simulation_engineer", "Simulation Engineer", "builds and validates simulations"),
        ("optimisation_solver", "Optimisation Solver", "formulates and solves constrained optimisation"),
        ("uncertainty_analyst", "Uncertainty Analyst", "propagates uncertainty and does sensitivity analysis"),
        ("hpc_engineer", "HPC Engineer", "parallelises and profiles compute-heavy workloads"),
        ("signal_analyst", "Signal Analyst", "analyses time and frequency domain data"),
        ("geospatial_analyst", "Geospatial Analyst", "works with projections, rasters and spatial joins"),
        ("physics_modeler", "Physics Modeler", "derives and checks physical models and units"),
        ("chemistry_modeler", "Chemistry Modeler", "models reactions and molecular properties"),
        ("climate_analyst", "Climate Analyst", "analyses climate and environmental datasets"),
        ("reproducibility_reviewer", "Reproducibility Reviewer", "verifies computational results can be reproduced"),
        ("units_checker", "Units Checker", "verifies dimensional consistency across calculations"),
    ],
    "bioinformatics": [
        ("sequence_analyst", "Sequence Analyst", "analyses nucleotide and protein sequences"),
        ("variant_analyst", "Variant Analyst", "calls and annotates genetic variants"),
        ("expression_analyst", "Expression Analyst", "analyses differential expression"),
        ("pathway_analyst", "Pathway Analyst", "performs enrichment and pathway analysis"),
        ("structure_analyst", "Structure Analyst", "analyses protein structure and folding predictions"),
        ("phylogenetics_analyst", "Phylogenetics Analyst", "builds and interprets trees"),
        ("single_cell_analyst", "Single-Cell Analyst", "processes and clusters single-cell data"),
        ("bio_pipeline_engineer", "Bio Pipeline Engineer", "builds reproducible genomics workflows"),
        ("bio_qc_analyst", "Bio QC Analyst", "runs quality control on sequencing runs"),
        ("clinical_genomics_analyst", "Clinical Genomics Analyst", "interprets variants against clinical databases"),
        ("microbiome_analyst", "Microbiome Analyst", "analyses community composition data"),
        ("bio_data_curator", "Bio Data Curator", "standardises metadata and ontologies"),
    ],
    "healthcare": [
        ("clinical_summariser", "Clinical Summariser", "summarises clinical documentation"),
        ("medical_literature_reviewer", "Medical Literature Reviewer", "reviews clinical evidence with study quality"),
        ("care_pathway_designer", "Care Pathway Designer", "maps care pathways and handoffs"),
        ("coding_specialist", "Medical Coding Specialist", "maps documentation to ICD/CPT codes"),
        ("health_data_analyst", "Health Data Analyst", "analyses population and outcome data"),
        ("trial_design_reviewer", "Trial Design Reviewer", "reviews protocol design and endpoints"),
        ("patient_comms_writer", "Patient Communications Writer", "writes plain-language patient materials"),
        ("regulatory_submission_writer", "Regulatory Submission Writer", "drafts regulatory submission sections"),
        ("pharmacovigilance_analyst", "Pharmacovigilance Analyst", "reviews adverse event signals"),
        ("health_privacy_reviewer", "Health Privacy Reviewer", "reviews PHI handling in workflows"),
        ("clinical_decision_support_designer", "CDS Designer", "designs decision support rules and alerts"),
        ("health_interop_engineer", "Health Interop Engineer", "works with FHIR/HL7 interoperability"),
    ],
    "legal": [
        ("contract_drafter", "Contract Drafter", "drafts contract clauses and structures"),
        ("contract_reviewer", "Contract Reviewer", "reviews contracts against a playbook"),
        ("ip_analyst", "IP Analyst", "analyses IP ownership and licensing"),
        ("licence_reviewer", "Licence Reviewer", "reviews open-source licence compatibility"),
        ("regulatory_analyst", "Regulatory Analyst", "maps regulatory obligations to operations"),
        ("employment_law_analyst", "Employment Law Analyst", "reviews employment terms and policy"),
        ("dispute_analyst", "Dispute Analyst", "summarises positions, risks and options"),
        ("terms_author", "Terms Author", "drafts terms of service and acceptable use"),
        ("privacy_notice_author", "Privacy Notice Author", "drafts privacy notices"),
        ("corporate_analyst", "Corporate Analyst", "reviews entity structure and governance documents"),
        ("compliance_gap_analyst", "Compliance Gap Analyst", "identifies gaps against obligations"),
        ("legal_research_assistant", "Legal Research Assistant", "locates and summarises authority"),
    ],
    "finance": [
        ("financial_modeler", "Financial Modeler", "builds three-statement and scenario models"),
        ("valuation_analyst", "Valuation Analyst", "builds DCF and comparables valuations"),
        ("budget_planner", "Budget Planner", "builds budgets and variance analysis"),
        ("unit_economics_analyst", "Unit Economics Analyst", "models CAC, LTV and contribution margin"),
        ("cashflow_analyst", "Cashflow Analyst", "forecasts liquidity and runway"),
        ("investment_analyst", "Investment Analyst", "analyses opportunities and risk-return"),
        ("risk_analyst", "Financial Risk Analyst", "quantifies market, credit and operational risk"),
        ("fundraising_analyst", "Fundraising Analyst", "models dilution and instrument terms"),
        ("treasury_analyst", "Treasury Analyst", "analyses cash management and FX exposure"),
        ("pricing_modeler", "Pricing Modeler", "models pricing scenarios and elasticity"),
        ("kpi_analyst", "Financial KPI Analyst", "defines and tracks financial KPIs"),
        ("board_reporting_writer", "Board Reporting Writer", "prepares board financial narratives"),
    ],
    "accounting": [
        ("bookkeeper", "Bookkeeper", "classifies transactions and reconciles accounts"),
        ("reconciliation_analyst", "Reconciliation Analyst", "reconciles ledgers and resolves breaks"),
        ("revenue_recognition_analyst", "Revenue Recognition Analyst", "applies revenue recognition rules"),
        ("expense_analyst", "Expense Analyst", "reviews expense categorisation and policy"),
        ("payroll_analyst", "Payroll Analyst", "reviews payroll calculations and deductions"),
        ("tax_analyst", "Tax Analyst", "analyses tax positions and filings"),
        ("audit_preparer", "Audit Preparer", "prepares schedules and support for audit"),
        ("internal_controls_reviewer", "Internal Controls Reviewer", "reviews segregation of duties and controls"),
        ("fixed_asset_analyst", "Fixed Asset Analyst", "manages capitalisation and depreciation"),
        ("close_coordinator", "Close Coordinator", "runs month-end close checklists"),
        ("ap_ar_analyst", "AP/AR Analyst", "manages payables and receivables ageing"),
        ("financial_statement_writer", "Financial Statement Writer", "drafts statements and notes"),
    ],
    "marketing": [
        ("positioning_strategist", "Positioning Strategist", "defines positioning and messaging"),
        ("content_strategist", "Content Strategist", "plans content themes and calendars"),
        ("seo_specialist", "SEO Specialist", "researches keywords and on-page structure"),
        ("copywriter", "Copywriter", "writes landing, ad and email copy"),
        ("email_marketer", "Email Marketer", "designs lifecycle and campaign sequences"),
        ("social_strategist", "Social Strategist", "plans channel-native social content"),
        ("brand_writer", "Brand Writer", "defines voice, tone and brand narrative"),
        ("campaign_analyst", "Campaign Analyst", "measures and optimises campaigns"),
        ("growth_experimenter", "Growth Experimenter", "designs acquisition experiments"),
        ("community_manager", "Community Manager", "plans community programmes and engagement"),
        ("pr_writer", "PR Writer", "drafts announcements and press materials"),
        ("case_study_writer", "Case Study Writer", "writes customer proof stories"),
    ],
    "sales": [
        ("prospect_researcher", "Prospect Researcher", "researches accounts and buying signals"),
        ("outreach_writer", "Outreach Writer", "writes personalised outreach sequences"),
        ("discovery_planner", "Discovery Call Planner", "prepares discovery questions and agenda"),
        ("proposal_writer", "Proposal Writer", "drafts proposals and scopes"),
        ("rfp_responder", "RFP Responder", "answers RFP questionnaires accurately"),
        ("objection_handler", "Objection Handler", "prepares evidence-backed objection responses"),
        ("pricing_negotiator", "Pricing Negotiator", "prepares negotiation positions and concessions"),
        ("pipeline_analyst", "Pipeline Analyst", "analyses pipeline health and conversion"),
        ("account_planner", "Account Planner", "builds expansion and retention plans"),
        ("battlecard_writer", "Battlecard Writer", "writes competitive battlecards"),
        ("demo_scripter", "Demo Scripter", "scripts value-led product demos"),
        ("renewal_analyst", "Renewal Analyst", "analyses renewal risk and actions"),
    ],
    "customer_support": [
        ("ticket_triager", "Ticket Triager", "classifies and routes incoming tickets"),
        ("response_writer", "Support Response Writer", "writes clear, empathetic responses"),
        ("kb_author", "Knowledge Base Author", "writes self-service help articles"),
        ("escalation_analyst", "Escalation Analyst", "assesses severity and escalation paths"),
        ("bug_reporter", "Bug Reporter", "turns reports into reproducible engineering tickets"),
        ("sentiment_analyst", "Support Sentiment Analyst", "tracks satisfaction and frustration signals"),
        ("macro_designer", "Macro Designer", "builds reusable response templates"),
        ("churn_signal_analyst", "Churn Signal Analyst", "flags at-risk accounts from support data"),
        ("onboarding_support_specialist", "Onboarding Support Specialist", "guides new users through setup"),
        ("support_metrics_analyst", "Support Metrics Analyst", "analyses resolution time and deflection"),
        ("multilingual_support_writer", "Multilingual Support Writer", "adapts responses across languages"),
        ("support_qa_reviewer", "Support QA Reviewer", "reviews response quality against rubric"),
    ],
    "human_resources": [
        ("job_description_writer", "Job Description Writer", "writes accurate, inclusive job descriptions"),
        ("interview_designer", "Interview Designer", "designs structured interview loops and rubrics"),
        ("candidate_evaluator", "Candidate Evaluator", "evaluates evidence against a rubric"),
        ("onboarding_designer", "Employee Onboarding Designer", "designs 30/60/90 onboarding plans"),
        ("compensation_analyst", "Compensation Analyst", "benchmarks and models compensation"),
        ("performance_reviewer", "Performance Review Writer", "drafts evidence-based reviews"),
        ("hr_policy_author", "HR Policy Author", "drafts employee policy and handbooks"),
        ("engagement_analyst", "Engagement Analyst", "analyses survey data and themes"),
        ("learning_designer", "Learning & Development Designer", "designs skill development paths"),
        ("succession_planner", "Succession Planner", "maps critical roles and successors"),
        ("hr_compliance_reviewer", "HR Compliance Reviewer", "reviews process against employment obligations"),
        ("internal_comms_writer", "Internal Comms Writer", "drafts internal announcements"),
    ],
    "operations": [
        ("process_designer", "Process Designer", "designs and documents operational processes"),
        ("sop_author", "SOP Author", "writes standard operating procedures"),
        ("workflow_automator", "Workflow Automator", "identifies and specifies automation opportunities"),
        ("vendor_manager", "Vendor Manager", "evaluates and manages supplier relationships"),
        ("inventory_analyst", "Inventory Analyst", "analyses stock levels and reorder points"),
        ("logistics_planner", "Logistics Planner", "plans routing, scheduling and fulfilment"),
        ("capacity_scheduler", "Capacity Scheduler", "schedules resources against demand"),
        ("quality_controller", "Quality Controller", "designs inspection and defect tracking"),
        ("procurement_analyst", "Procurement Analyst", "analyses sourcing options and terms"),
        ("facilities_planner", "Facilities Planner", "plans space, equipment and maintenance"),
        ("continuity_planner", "Business Continuity Planner", "plans for operational disruption"),
        ("ops_metrics_analyst", "Ops Metrics Analyst", "tracks throughput, cycle time and bottlenecks"),
    ],
    "analytics": [
        ("dashboard_designer", "Dashboard Designer", "designs decision-oriented dashboards"),
        ("sql_analyst", "SQL Analyst", "writes and validates analytical SQL"),
        ("funnel_analyst", "Funnel Analyst", "analyses conversion and drop-off"),
        ("attribution_analyst", "Attribution Analyst", "models channel attribution"),
        ("event_taxonomy_designer", "Event Taxonomy Designer", "designs consistent tracking schemas"),
        ("report_automator", "Report Automator", "automates recurring reporting"),
        ("kpi_reviewer", "KPI Reviewer", "audits metric definitions for correctness"),
        ("benchmarking_analyst", "Benchmarking Analyst", "compares performance to baselines"),
        ("data_qa_analyst", "Analytics QA Analyst", "validates numbers before publication"),
        ("self_serve_enabler", "Self-Serve Enabler", "builds documented datasets for non-analysts"),
        ("insight_writer", "Insight Writer", "writes concise, actionable insight summaries"),
        ("experiment_readout_writer", "Experiment Readout Writer", "writes honest experiment readouts"),
    ],
    "creative_writing": [
        ("story_architect", "Story Architect", "designs plot structure and arcs"),
        ("character_developer", "Character Developer", "develops character voice and motivation"),
        ("dialogue_writer", "Dialogue Writer", "writes natural, purposeful dialogue"),
        ("worldbuilder", "Worldbuilder", "builds internally consistent settings"),
        ("screenwriter", "Screenwriter", "writes scenes in screenplay format"),
        ("poet", "Poet", "writes original poetry with deliberate form"),
        ("essayist", "Essayist", "writes argumentative and reflective essays"),
        ("humour_writer", "Humour Writer", "writes comedic material with timing"),
        ("script_doctor", "Script Doctor", "diagnoses and repairs structural problems"),
        ("line_editor", "Line Editor", "edits at sentence level for rhythm and clarity"),
        ("developmental_editor", "Developmental Editor", "edits for structure, pacing and theme"),
        ("blurb_writer", "Blurb Writer", "writes hooks, synopses and jacket copy"),
    ],
    "media_production": [
        ("video_scripter", "Video Scripter", "writes video scripts with shot direction"),
        ("storyboard_describer", "Storyboard Describer", "describes shot-by-shot storyboards"),
        ("podcast_producer", "Podcast Producer", "plans episodes, segments and show notes"),
        ("audio_editor", "Audio Editor", "specifies edits, levels and mastering targets"),
        ("subtitle_writer", "Subtitle Writer", "writes timed, readable subtitles"),
        ("thumbnail_strategist", "Thumbnail Strategist", "designs thumbnail and title strategy"),
        ("interview_producer", "Interview Producer", "prepares interview arcs and questions"),
        ("motion_designer", "Motion Designer", "specifies motion graphics and transitions"),
        ("colour_grader", "Colour Grader", "specifies grading looks and consistency"),
        ("media_asset_manager", "Media Asset Manager", "organises footage, naming and archives"),
        ("distribution_planner", "Distribution Planner", "plans multi-platform release and formats"),
        ("livestream_producer", "Livestream Producer", "plans run-of-show and technical setup"),
    ],
    "education": [
        ("curriculum_designer", "Curriculum Designer", "designs learning objectives and sequences"),
        ("lesson_planner", "Lesson Planner", "plans individual lessons with activities"),
        ("assessment_writer", "Assessment Writer", "writes aligned assessments and rubrics"),
        ("explainer", "Concept Explainer", "explains concepts at a chosen level"),
        ("worked_example_author", "Worked Example Author", "writes step-by-step worked examples"),
        ("misconception_analyst", "Misconception Analyst", "identifies and addresses common misconceptions"),
        ("practice_generator", "Practice Generator", "generates graded practice problems"),
        ("feedback_writer", "Learner Feedback Writer", "writes specific, actionable learner feedback"),
        ("accessibility_adapter", "Learning Accessibility Adapter", "adapts material for diverse needs"),
        ("study_planner", "Study Planner", "builds spaced, realistic study schedules"),
        ("tutor", "Tutor", "guides a learner through problems with questions"),
        ("credential_mapper", "Credential Mapper", "maps content to standards and outcomes"),
    ],
    "blockchain": [
        ("contract_developer", "Smart Contract Developer", "writes contracts with explicit invariants"),
        ("contract_auditor", "Smart Contract Auditor", "audits for reentrancy, overflow and access flaws"),
        ("tokenomics_designer", "Tokenomics Designer", "models supply, incentives and sinks"),
        ("protocol_designer", "Protocol Designer", "designs consensus and protocol mechanics"),
        ("gas_optimiser", "Gas Optimiser", "reduces execution cost in contracts"),
        ("bridge_reviewer", "Bridge Reviewer", "reviews cross-chain trust assumptions"),
        ("wallet_engineer", "Wallet Engineer", "implements key handling and signing flows"),
        ("indexer_engineer", "Indexer Engineer", "indexes on-chain events into queryable stores"),
        ("defi_analyst", "DeFi Analyst", "analyses liquidity, oracles and liquidation risk"),
        ("onchain_forensics_analyst", "On-Chain Forensics Analyst", "traces flows and clusters addresses"),
        ("governance_designer", "Governance Designer", "designs proposal and voting mechanics"),
        ("chain_compliance_reviewer", "Chain Compliance Reviewer", "reviews regulatory exposure of on-chain design"),
    ],
    "localization": [
        ("translator", "Translator", "translates preserving meaning and register"),
        ("localiser", "Localiser", "adapts content to local conventions and culture"),
        ("terminology_manager", "Terminology Manager", "maintains consistent bilingual glossaries"),
        ("transcreation_writer", "Transcreation Writer", "rewrites marketing copy for a new market"),
        ("locale_qa_reviewer", "Locale QA Reviewer", "reviews formatting, truncation and layout"),
        ("rtl_specialist", "RTL Specialist", "adapts layouts for right-to-left scripts"),
        ("date_number_formatter", "Format Specialist", "normalises dates, numbers and currency"),
        ("voice_consistency_reviewer", "Voice Consistency Reviewer", "keeps brand voice across locales"),
        ("legal_localisation_reviewer", "Legal Localisation Reviewer", "flags locale-specific legal wording"),
        ("subtitle_localiser", "Subtitle Localiser", "localises subtitles within timing limits"),
        ("keyword_localiser", "Keyword Localiser", "researches market-specific search terms"),
        ("pseudo_localisation_tester", "Pseudo-Localisation Tester", "tests UI resilience to string expansion"),
    ],
    "orchestration": [
        ("goal_decomposer", "Goal Decomposer", "decomposes goals into an executable task graph"),
        ("team_assembler", "Team Assembler", "selects the minimal agent team for a goal"),
        ("dependency_planner", "Dependency Planner", "orders work and maximises safe parallelism"),
        ("progress_monitor", "Progress Monitor", "tracks progress against the plan and flags drift"),
        ("replanner", "Replanner", "revises the plan when assumptions break"),
        ("budget_governor", "Budget Governor", "keeps execution inside token and cost budgets"),
        ("critic", "Critic", "rejects weak output and issues specific repair instructions"),
        ("final_verifier", "Final Verifier", "verifies acceptance criteria before completion"),
        ("conflict_resolver", "Conflict Resolver", "reconciles contradictory agent outputs"),
        ("summariser", "Summariser", "compresses long context without losing decisions"),
        ("checkpointer", "Checkpointer", "records resumable state at milestones"),
        ("escalation_router", "Escalation Router", "decides when to escalate to human or stronger model"),
    ],
}

CAP_TIER = {
    "code": {"backend_engineering", "frontend_engineering", "mobile_engineering", "game_development",
             "embedded_systems", "data_engineering", "machine_learning", "mlops", "devops",
             "quality_assurance", "database", "blockchain", "cloud_infrastructure"},
    "reasoning": {"software_architecture", "security", "research", "legal", "finance", "accounting",
                  "scientific_computing", "orchestration", "privacy_compliance", "data_science",
                  "healthcare", "bioinformatics", "site_reliability"},
}

# roles that must never run unattended
HUMAN_GATE_ROLES = {
    "migration_planner", "mobile_release_engineer", "cd_engineer", "release_manager",
    "model_deployer", "shadow_deploy_engineer", "dr_engineer", "chaos_engineer",
    "contract_drafter", "terms_author", "tax_analyst", "payroll_analyst",
    "regulatory_submission_writer", "clinical_decision_support_designer",
    "contract_developer", "bridge_reviewer", "wallet_engineer", "escalation_router",
}


def capability_for(domain: str) -> str:
    for tier, doms in CAP_TIER.items():
        if domain in doms:
            return tier
    return "general"


def instructions(domain: str, name: str, does: str, verify: str) -> str:
    dom = domain.replace("_", " ")
    return (
        f"You are the {name}, a specialist in {dom}. You {does}.\n"
        "Work to this contract:\n"
        "1. Restate the part of the goal you own, and name the assumptions you are making.\n"
        "2. Produce the concrete deliverable — not a description of the deliverable.\n"
        "3. Mark anything you could not verify as an explicit open question rather than guessing.\n"
        "4. State what the next agent needs from you, as structured fields.\n"
        f"Your output is checked by {verify} verification, so make it checkable: "
        "specific, self-consistent, and free of unsupported claims."
    )


def build() -> list[dict]:
    agents: list[dict] = []
    seen: set[str] = set()
    for domain, roles in ROLES.items():
        meta = DOMAINS[domain]
        for slug, name, does in roles:
            aid = f"{domain}.{slug}"
            if aid in seen:
                raise ValueError(f"duplicate agent id {aid}")
            seen.add(aid)
            caps = sorted(set(meta["caps"] + [domain, slug.split("_")[0]]))
            perms = list(meta["perms"])
            if slug in HUMAN_GATE_ROLES and "human_gate" not in perms:
                perms.append("human_gate")
            agents.append({
                "id": aid,
                "name": name,
                "domain": domain,
                "description": f"{name} — {does}.",
                "capabilities": caps,
                "tools": list(meta["tools"]),
                "model_requirements": {"capability": capability_for(domain)},
                "cost_level": meta["cost"],
                "risk_level": meta["risk"],
                "permissions": perms,
                "system_instructions": instructions(domain, name, does, meta["verify"]),
                "verification_strategy": meta["verify"],
                "human_gate": slug in HUMAN_GATE_ROLES,
            })
    return agents


# Aliases keep the original 16 short ids working so existing plans/tests don't break.
ALIASES = {
    "goal_analyzer": "product_management.goal_analyzer",
    "requirements": "product_management.requirements_writer",
    "architecture": "software_architecture.system_designer",
    "researcher": "research.technical_researcher",
    "analyst": "data_science.data_storyteller",
    "ui": "ux_design.flow_designer",
    "frontend": "frontend_engineering.component_builder",
    "backend": "backend_engineering.api_implementer",
    "database": "database.schema_designer",
    "ai_integrator": "machine_learning.rag_engineer",
    "security": "security.appsec_reviewer",
    "testing": "quality_assurance.unit_test_writer",
    "devops": "devops.ci_engineer",
    "deployment": "devops.release_manager",
    "critic": "orchestration.critic",
    "final_verifier": "orchestration.final_verifier",
}

if __name__ == "__main__":
    agents = build()
    for a in agents:
        assert re.fullmatch(r"[a-z0-9_.]+", a["id"]), a["id"]
        assert a["system_instructions"].strip()
        assert a["verification_strategy"] in {"factual", "code", "tests", "security", "quality", "completion"}
        assert a["cost_level"] in {"low", "medium", "high"}
        assert a["risk_level"] in {"low", "medium", "high"}
    out = {"version": 1, "aliases": ALIASES, "agents": agents}
    Path("agents.json").write_text(json.dumps(out, indent=1))
    doms = {}
    for a in agents:
        doms[a["domain"]] = doms.get(a["domain"], 0) + 1
    print(f"wrote agents.json: {len(agents)} agents across {len(doms)} domains")
    print(f"human-gated: {sum(1 for a in agents if a['human_gate'])}")
